### ISSUE TITLE
統計表に旧番号が重複など

### ISSUE THREAD

**Issue by dalaoshi-huster** [swsoyee/2019-ncov-japan#1]
- 最後のまとめ表に厚労省の旧番号が重複しています。データの読み取りに支障があります。
　

- まとめ表に千葉県のデータと厚労省が２０２０・２・１７　に更新したデータと不一致があります。新番号の5号ケースは中国武漢市在住のはずです。

ご参考までに

**Comment by swsoyee** [comment]
ご報告ありがとうございます。

> 最後のまとめ表に厚労省の旧番号が重複しています。データの読み取りに支障があります。

先頭の番号は行数の番号で、旧番号とは別物です。`行数`の列名を追加する方針で今夜修正します。

> まとめ表に千葉県のデータと厚労省が２０２０・２・１７　に更新したデータと不一致があります。 新番号の5号ケースは中国武漢市在住のはずです。

国内事例の新番号とチャーター便の新番号は別系統になっています。
厚生労働省のデータによると、
国内事例の新番号５番の患者の居住地は武漢在住で、チャーター便の新番号５番の患者の居住地は千葉です。間違いはありませんと思いますが、もう一度チェック頂いてもよろしいでしょうか。

**Comment by swsoyee** [comment]
@dalaoshi-huster 番号の修正が完了しましたので、該当IssueをCloseします。
