### ISSUE TITLE
東京都の市区町村別の時系列データ

### ISSUE THREAD

**Issue by TomonoriHoshi** [swsoyee/2019-ncov-japan#1167]
以下は東京都の時系列データ等が見つからず自分で手入力していました。東京都の市区町村別の時系列データをオフィシャルサイトから入力しているのですが、現在、ビジュアライゼーションを含めて、私の方ではデータをあまり使いこなせていない状態です。

https://github.com/TomonoriHoshi/tokyoCOVID-19

こちらでデータを有効活用してもらえるなら、それが良いように思いコンタクトを送りました。この手のデータは、こちらのサイトで需要ありますか？

**Comment by swsoyee** [comment]
Issueありがどうございます。またデータの提供にも感謝しております。
最近は結構忙しく、新規機能の開発は暫く中止しております。本当にすみません。🙇🏻‍♂️

**Comment by TomonoriHoshi** [comment]
お忙しいところ返信ありがとうございます。了解しました。データの有効活用こちらの方で引き続き検討を進めていきます。こちらCloseしておきます。
