### ISSUE TITLE
about 症状程度的表示

### ISSUE THREAD

**Issue by dalaoshi-huster** [swsoyee/2019-ncov-japan#12]
厚生省在2月17日公开了当前收治患者的症状表现，比较详细，相信今后会有类似数据继续出炉。
建议按照丁香园对中国新冠肺炎患者数据的统计，以A 黄色作为疑似（隔离人数？）人数，
B棕色为确诊人数，
C绿色为痊愈人数，
D红色为需要借助人工插管或者进入ICU监护的重症or危重（重篤状態）的人数，
E黑色为死亡人数，
大致分为五类,方便用户迅速了解疫情。
例如2月17日数据 (クルーズ船を除く)（见   https://www.mhlw.go.jp/stf/newpage_09571.html   ）可以分为：
PCR陽性:59
完治退院：19
重症：3
死亡：1

鉴于信息不充分，尚且难以掌握疑似病例人数。可否以正在健康观察中人数代替？

**Comment by swsoyee** [comment]
@dalaoshi-huster 以2月17日的数据为例，
![image](https://user-images.githubusercontent.com/20528423/74719243-0663a180-5277-11ea-9373-a6c824ed4e83.png)

按下述格式收集成`beHospitalized.csv`
|date | mild | severe | unknow |
|---| ---| --- | ---|
|   20200217  | X | X | X |
|   20200218  | X | X | X |

等等即可。

> - mild：うち軽〜中等症の者
> - severe：うち人工呼吸器……
> - uknow：うち確認中

**Comment by dalaoshi-huster** [comment]
日付　　　　　　　無症状者　　軽・中症状者　　重症者　　確認中
2020年2月１７日　　　12　　　　　　23　　　　　3　　　　　4



这样？

**Comment by swsoyee** [comment]
@dalaoshi-huster 参考
https://github.com/swsoyee/2019-ncov-japan/blob/master/Data/recovered.csv
记录每日增加数即可，列名用英文即可，日期+3分类*2（国内+飞机）
一共7列的数据

**Comment by dalaoshi-huster** [comment]
[patients' level.xlsx](https://github.com/swsoyee/2019-ncov-japan/files/4219253/patients.level.xlsx)

这样？

**Comment by dalaoshi-huster** [comment]
[patients' level.xlsx](https://github.com/swsoyee/2019-ncov-japan/files/4219450/patients.level.xlsx)
  
update to 18thFeb

**Comment by dalaoshi-huster** [comment]
[patients' level.xlsx](https://github.com/swsoyee/2019-ncov-japan/files/4228168/patients.level.xlsx)

2月19日までのデータを更新しました。

**Comment by swsoyee** [comment]
@dalaoshi-huster 
1. 保持一行只有一个数据，否则不方便数据的读取。
2. 另外可以直接粘贴CSV，不需要上传xlsx，不够直观。
3. 需要第一份数据到最新一份到数据，不是2月17日开始到数据

## 参考
date | mild-domestic | severe-domestic | ongoing-domestic | mild-flight | severe-flight | ongoing-flight | mild-ship | severe-ship | ongoing-ship
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
20200115 |   |   |   |   |   |   |   |   |  
20200116 |   |   |   |   |   |   |   |   |  
20200117 |   |   |   |   |   |   |   |   |  
20200118 |   |   |   |   |   |   |   |   |  
20200119 |   |   |   |   |   |   |   |   |  
20200120 |   |   |   |   |   |   |   |   |  
20200121 |   |   |   |   |   |   |   |   |  
20200122 |   |   |   |   |   |   |   |   |  
20200123 |   |   |   |   |   |   |   |   |  
20200124 |   |   |   |   |   |   |   |   |  
20200125 |   |   |   |   |   |   |   |   |  
20200126 |   |   |   |   |   |   |   |   |  
20200127 |   |   |   |   |   |   |   |   |  
20200128 |   |   |   |   |   |   |   |   |  
20200129 |   |   |   |   |   |   |   |   |  
20200130 |   |   |   |   |   |   |   |   |  
20200131 |   |   |   |   |   |   |   |   |  
20200201 |   |   |   |   |   |   |   |   |  
20200202 |   |   |   |   |   |   |   |   |  
20200203 |   |   |   |   |   |   |   |   |  
20200204 |   |   |   |   |   |   |   |   |  
20200205 |   |   |   |   |   |   |   |   |  
20200206 |   |   |   |   |   |   |   |   |  
20200207 |   |   |   |   |   |   |   |   |  
20200208 |   |   |   |   |   |   |   |   |  
20200209 |   |   |   |   |   |   |   |   |  
20200210 |   |   |   |   |   |   |   |   |  
20200211 |   |   |   |   |   |   |   |   |  
20200212 |   |   |   |   |   |   |   |   |  
20200213 |   |   |   |   |   |   |   |   |  
20200214 |   |   |   |   |   |   |   |   |  
20200215 |   |   |   |   |   |   |   |   |  
20200216 |   |   |   |   |   |   |   |   |  
20200217 |   |   |   |   |   |   |   |   |  
20200218 |   |   |   |   |   |   |   |   |  
20200219 |   |   |   |   |   |   |   |   |  
20200220 |   |   |   |   |   |   |   |   |  

## 模版
```csv
date,mild-domestic,severe-domestic,ongoing-domestic,mild-flight,severe-flight,ongoing-flight,mild-ship,severe-ship,ongoing-ship
20200115,,,,,,,,,
20200116,,,,,,,,,
20200117,,,,,,,,,
20200118,,,,,,,,,
20200119,,,,,,,,,
20200120,,,,,,,,,
20200121,,,,,,,,,
20200122,,,,,,,,,
20200123,,,,,,,,,
20200124,,,,,,,,,
20200125,,,,,,,,,
20200126,,,,,,,,,
20200127,,,,,,,,,
20200128,,,,,,,,,
20200129,,,,,,,,,
20200130,,,,,,,,,
20200131,,,,,,,,,
20200201,,,,,,,,,
20200202,,,,,,,,,
20200203,,,,,,,,,
20200204,,,,,,,,,
20200205,,,,,,,,,
20200206,,,,,,,,,
20200207,,,,,,,,,
20200208,,,,,,,,,
20200209,,,,,,,,,
20200210,,,,,,,,,
20200211,,,,,,,,,
20200212,,,,,,,,,
20200213,,,,,,,,,
20200214,,,,,,,,,
20200215,,,,,,,,,
20200216,,,,,,,,,
20200217,,,,,,,,,
20200218,,,,,,,,,
20200219,,,,,,,,,
20200220,,,,,,,,,
```

**Comment by dalaoshi-huster** [comment]
好的。
数据起点在1月16日但是2月4日以前并没有关于患者患病程度 的描述，只有症状描述。不知如何分类？

**Comment by swsoyee** [comment]
1. 统计unique(症状描述)
2. 重新规划到mild、severe、ongoing三分类中
3. 写备注说明上述分类情况

即可

**Comment by dalaoshi-huster** [comment]
2月4日以前没有统计患者总数，也没有具体的出院信息。2月4日以后有总的人数信息，此前只是按照个例通报（通报中只有他们就诊前和就诊时的症状，没有入院后的信息）。因此很难统计此前某日共有多少人处于住院状态，也难以跟踪他们的症状恶化或者改善。
是否重新以2月4日为起始点？

**Comment by swsoyee** [comment]
@dalaoshi-huster 那你先把2月4日以后的数据统计出来用着先吧，后期再补
