### ISSUE TITLE
No more updates since 2022-09-05

### ISSUE THREAD

**Issue by eguidotti** [swsoyee/2019-ncov-japan#16936]
Hi @swsoyee, it seems the last update of the data was on 05 September 2022. Would it be possible to fix that?
See also https://github.com/covid19datahub/COVID19/issues/211
Many thanks! 
Emanuele

**Comment by eguidotti** [comment]
Thank you for the info! That works perfectly fine of course

> the government has officially provided public data sets

Would you be able to provide the link(s) to these datasets? I would be interested in integrating them in my project

**Comment by swsoyee** [comment]
@eguidotti Sorry for the late response.
You could check some data provide by a Japanese media:
https://toyokeizai.net/sp/visual/tko/covid19/en.html

They provide some csv files based on data released by the government.

**Comment by eguidotti** [comment]
Excellent! This will be very useful.
Thank you for your response and for your work.
All the best, Emanuele
