### ISSUE TITLE
28日のデータあってます？

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#1798]
https://news.yahoo.co.jp/articles/48b865cb232875a1c698b50c7d8ef6327421be92

> 新型コロナウイルスの感染者は28日、毎日新聞集計で全国で新たに995人が確認され、これまで最多だった981人（7月23日）を上回り、過去最多を更新した。

**Comment by swsoyee** [comment]
こちらは熊本のデータによるズレです。
毎日新聞集計の`熊本36名`うちの14名は27日の夜に先行報道があったため、27日の分に入っています。
従った、[28日の熊本の新規感染者は22名になります。](https://this.kiji.is/660829772782748769?c=92619697908483575)

**Comment by Lix900** [comment]
ありがとうございます。

日本はちゃんとした数字も出せないだろうか。。
