### ISSUE TITLE
疑问待核对

### ISSUE THREAD

**Issue by pennyzz** [swsoyee/2019-ncov-japan#18]
20200218 厚生省公布的第59号爱知县60代男性病例
是否为已统计的20200217第53号病例
从爱知县自己公布的病例中核对不到，或者因为均为60代男性（中央地方编号有差别我没找准）
核心争议到底是17日确诊入院还是18日确诊入院（链接3与前两个有出入）
链接1:厚生省数据
https://www.mhlw.go.jp/stf/newpage_09609.html
链接2:厚生省网站附件的爱知县数据报告
https://www.mhlw.go.jp/content/10906000/000597568.pdf
链接3:根据报告来源（爱知县政府健康政策课公告）
https://www.pref.aichi.jp/soshiki/kenkotaisaku/pressrelease-ncov200217.html

**Comment by swsoyee** [comment]
@pennyzz 有疑问的是否是下述数据？

https://github.com/swsoyee/2019-ncov-japan/blob/master/Data/detail.csv#L45

该文件的第45行：
```
53	44	20200217	60	男	愛知	44	調査中	実施	国内事例	患者の知人	48
```

回答：
20200218 厚生省公布的第59号爱知县60代男性病例仍未汇总在表格中，因此这两者不为同一个人。
该例病人的数据应该预计在厚生省今天晚上即将公布的：

**新型コロナウイルス感染症の現在の状況と厚生労働省の対応について（令和２年２月19日版）**

页面中出现，届时可以核对一下。
如果问题得到解答可以点击右下角的Close按钮关闭该Issue。
