### ISSUE TITLE
岩手のデータ間違ってません？

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#1895]
![image](https://user-images.githubusercontent.com/64581074/89008934-8887e400-d346-11ea-9c98-1dc939803332.png)

**Comment by swsoyee** [comment]
いつもありがどうございます。ちょっと曖昧な説明を「感染者ゼロの都道府県」の一番したに書いていますが、現在感染者数は：
厚労省発表の感染者数 - 厚労省発表の回復者数 - 厚労省発表の死亡者数
で計算をしています。

厚労省の昨日の分の発表によると、岩手の感染者数、入院者数、退院者数はまだ０のままなので、こちらにも酷くラグが出てきました。
https://www.mhlw.go.jp/content/10906000/000654091.pdf
多分今日はちゃんと更新されるので、本日の夕方からこちらも更新されるはずと思います。
