### ISSUE TITLE
403/404 error

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#1906]
![image](https://user-images.githubusercontent.com/64581074/89021335-53d25780-d35b-11ea-991e-b3444c2ebc93.png)
![image](https://user-images.githubusercontent.com/64581074/89021342-57fe7500-d35b-11ea-9a30-2fc3933c47ae.png)

**Comment by swsoyee** [comment]
おそらくちょうどデータ更新中です。最近アクセスがまた増えてきて、たまに重い時があります。
再度アクセスしてみてください。それでも見れなければ、お手数ですがキャッシュをクリアして試してください。

**Comment by Lix900** [comment]
HAとかやってないですね。いつもありがとうございます。
