### ISSUE TITLE
关于进度的确认

### ISSUE THREAD

**Issue by dalaoshi-huster** [swsoyee/2019-ncov-japan#20]
@penneyy 以及我在试图跟上今天即将出炉的进度，不过目前不清楚 @swsoyee 的信息整理到达哪一个阶段，为了避免重复劳动，特此询问。

以及出现NHK等大型媒体的报道比厚生省更加速度快，且信息更丰富的情况，是否采用媒体信息？

**Comment by swsoyee** [comment]
@dalaoshi-huster 目前是我在根据媒体信息更新数据，更新数据的时候：

1. 修改summary.csv中的数字
2. 在mhlw_houdou.csv更新数据来源（新闻标题、链接等）
3. 等晚上厚生省出报告后，更换mhlw_houdou.csv中记录的消息来源，变更为厚生省的链接
4. 晚上核查每日汇总报告，更新detail.csv（该文件中报告的数值会晚一天，当天数据在隔天更新）
5. 核对其他媒体和同类应用，数值上是否有差错。19号的数值我已经更新了。

**Comment by pennyzz** [comment]
请问从哪里看其他人已经添加的信息，很担心没看到会重复添加。是从issue 按时间序列看吗

**Comment by pennyzz** [comment]
比如，这里是已经有人更新了吗

**Comment by swsoyee** [comment]
@pennyzz issue还是open状态的话证明这个问题还没有解决，现在需要有人来追踪更新detail.csv文件，我自己更新有点力不从心了，所以20号的数据还没有更新。 @dalaoshi-huster 目前工作流程还没形成，信息流也很乱，即使是重复性工作也具有信息核对意义。

这个项目并不会有报酬，所以也不太清楚大家会花多少时间在上面，所以也就不好意思push。
