### ISSUE TITLE
感染者数についての質問、厚労省の数との差はなんでしょうか？

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#2351]
https://www.mhlw.go.jp/stf/newpage_12910.html

> ８月10日0:00現在、検査陽性者47,990例が確認されている。

サイトの感染者数51,092には10日の839と11日の速報値600も入っていると思いますが、それにしても、差があまりにも大きいのはなぜでしょうか？

NHKまとめは5万1156人と大体あってますが、厚労省の数との差はなんでしょうか？

**Comment by swsoyee** [comment]
現在のサイトの方の感染者数：
国内の感染者数（リアルタイム、クルーズ船を含まない）：50384
に対して、昨日まとめ時までの感染者数（厚労省発表）は：47990

差は (50384 - 本日のリアルタイム分 700 - 昨日のリアルタイム分 839) - 47990 = 855 名。
その内、愛知県の感染者数はここ数日更新されていないらしい（約600名）。
![image](https://user-images.githubusercontent.com/20528423/89902952-0939c080-dc22-11ea-872c-66a6117690ea.png)

他にも京都、静岡、山梨など連休中のデータは更新していないによるズレ
と再陽性患者の数によるズレがあります。

**Comment by Lix900** [comment]
ありがとうございます。
