### ISSUE TITLE
【バージョン対応】shinydashboardPlus

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#2623]
@Bob-FU branch: https://github.com/swsoyee/2019-ncov-japan/tree/fix-shinydashboardplus-new-version

**Comment by swsoyee** [comment]
@Bob-FU Fu哥这个问题最近能解决嘛，可能先Merge再推文章会好一点
https://github.com/cosname/cosx.org/pull/907#issuecomment-691010598

**Comment by Bob-FU** [comment]
@swsoyee 这个周末，明后天上线测试一下看看。
