### ISSUE TITLE
想咨询一下您关于2.4日的数据

### ISSUE THREAD

**Issue by marspalLiu** [swsoyee/2019-ncov-japan#27]
在2.4日您添加了3例新闻，分别为《2020-02-04 与新型冠状病毒有关的肺炎暴发（第17例）》《2020-02-04 新发冠状病毒伴发的肺炎患者暴发（第18例）》《2020-02-04 新型冠状病毒伴发的肺炎患者暴发
（第19例）》，可是您的感染人数变化表2.4日新增为2人。是不是出现错误了呢？

**Comment by swsoyee** [comment]
@marspalLiu 确实如您所言，目前的状况是这样的
1. 总数和NHK的完全一致；
2. 各省份的数字和NHK完全一致。

因此，可能性在某一个省份的单独数据列错了日期。

2月4日的确为新增3人，其中一人为中国旅游者，确诊时人已经回国，并且没有告知行动经过。
[参考链接](https://www.mhlw.go.jp/stf/newpage_09312.html)

另外两人1个为千叶确诊的旅游者，1个为撤侨的，因此数据可能出错在东京都的数据上。

在[東京都新型コロナウイルス感染症対策本部報](https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html)的页面上没有出现该名患者的报告，因此难以快速纠正是哪一天的统计数据出了问题。

目前其他的日本疫情Dashboard都没有明确列出各省份的每日数据导致我很难查找比对，
加之现在开发方面还有很多没有完成的部分，如果您能够帮助校正一下是最好的了。

**Comment by swsoyee** [comment]
@marspalLiu 另外，我再次核对了下数据，有可能媒体计算方法和厚生労働省的计算方法不同。
截止目前为止，厚生労働省报道的人数为239人
https://www.mhlw.go.jp/stf/newpage_09859.html
而NHK报道人数为（228+14）为242人https://www3.nhk.or.jp/news/html/20200301/k10012308361000.html
这3人之差需要核对（一路记下来的不知道为啥会有出入……）

**Comment by marspalLiu** [comment]
@swsoyee 好的，辛苦您了，我有时间也帮您排查一下，有消息会给您发信息。

**Comment by swsoyee** [comment]
@marspalLiu 谢谢～，另外NHK的柱状图显示2月4日也是新增2人。
https://www3.nhk.or.jp/news/special/coronavirus/
其他日期的我还没对比，也可能是别的日期出错了。

**Comment by marspalLiu** [comment]
@swsoyee 好的，感谢~，我再看看相关报道

**Comment by swsoyee** [comment]
重新以 https://newsdigest.jp/pages/coronavirus/ 为基准核对数据，确定重新修正2月4日为2人。
