### ISSUE TITLE
how to run this source code ?

### ISSUE THREAD

**Issue by longtran84** [swsoyee/2019-ncov-japan#33]

**Comment by swsoyee** [comment]
@longtran84 If you are not familiar with R, It's also quite simple.
1. Install R in your PC.
2. Install RStuido (Optional).
3. Install all the packages which are written in the `global.R`.
https://github.com/swsoyee/2019-ncov-japan/blob/master/global.R#L1-L15
4. Run `shiny::runGitHub("2019-ncov-japan", "swsoyee", launch.browser = TRUE)`, or clone the whole project into your PC, and Open the RStudio, open this project and just click the `Run App` button in `app.R` or `server.R`.

Also, you can follow this tutorial:
https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/

**Comment by inductor** [comment]
Can't this run on docker?

**Comment by swsoyee** [comment]
@inductor Maybe this is what your need? [wiki](https://github.com/swsoyee/2019-ncov-japan/wiki/%E8%A9%A6%E9%A8%93%E3%83%BB%E6%A4%9C%E8%A8%BC%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E6%96%B9%E6%B3%95-(Kubernetes))

**Comment by Bob-FU** [comment]
@inductor check out docker image of shiny server.
https://github.com/Bob-FU/shiny
