### ISSUE TITLE
Revised English translation

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#382]
# Methods of Text Revision

1. All (Not complete at the moment, pending a late correction and addition) text content is saved in [`translation.json`](https://github.com/swsoyee/2019-ncov-japan/blob/master/www/lang/translation.json) file.
2. You need to revise the English text in the `translation.json` file.
3. Just correct them, commit and create a PR to `master` branch.

**Comment by junderw** [comment]
Cursory glance looks good to me.

Are there certain specific phrases you are particularly worried about?

**Comment by swsoyee** [comment]
@junderw Thank you for your comment!
I not an English native speaker, so maybe some phrases and word are not are not very authentic.
Or maybe some of the sentences are harder to understand, and I'd like to fix them to make it easier to understand for English speaker.
Don't need a lot of fixes at once, just fix it if you see something that's not quite right☺️
