### ISSUE TITLE
感染者テーブルに残り列を追加

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#383]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/64581074/81997833-d9fbcd80-968b-11ea-8b88-b153d2c263e2.png">

↑の感染者数の隣に残り人数の列を追加

**Comment by swsoyee** [comment]
@Lix900 アドバイスありがどうございます！実装には難しくないが、こちらのテーブルの幅が少し足りなくなっていますので、どう表現するには少し考える必要がありますね。

もし何かアドバイスがありましたらご気軽におっしゃってください👍🏼

**Comment by Lix900** [comment]
@swsoyee コメントありがとうございます。個人的に関心あるのは合計、新規、残り、退院、死亡、致死率ですが、上のテーブルに感染推移や倍加日数、感染密度などはなくてもいいきがしますが。もしくは列の選択を可能にするのはいかがでしょうか？

**Comment by swsoyee** [comment]
@Lix900 了解しました。
> もしくは列の選択を可能にするのはいかがでしょうか？

この実装が難しくないですので、明日にリリースします👍🏼

**Comment by swsoyee** [comment]
![image](https://user-images.githubusercontent.com/20528423/82114270-af4a6b80-9796-11ea-8ba7-fb6be19b585e.png)
リリース完了
