### ISSUE TITLE
05-15の新規PCR検査数マイナスはなぜでしょうか？

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#389]

**Comment by swsoyee** [comment]
サイトの方に説明を追加しました。
まとめて言うと、5月8日から基準変更があったため、調整中のデータが結構あります、そのためマイナスと激増（厚労省が発表する前日比と違うこと）結構あります。

5/13新規18（厚労省の国内前日比約4500）：大阪などの数を約4000を減少しました。
5/14新規9000（厚労省の国内前日比約5000）：千葉県から県内の保健所設置市分の追加計上があったため。
5/15マイナス2000（厚労省の国内前日比約4400）：千葉県については保健所設置市分を重複して計上していたため、重複分を累計検査人数から減じている。神奈川県については計上を検査件数から検査人数にしたため、前日比は昨日の検査人数との差分を計上している。岐阜県については検査人数から退院時の確認検査人数を減じた数を本日分から計上しているが、前日分が不明のため、前日比を０としている。
5/16新規9000（厚労省の国内前日比約3700）：神奈川県の4月27日以前の精査中であった検査人数が確定し計上されたため、前日比はそれらの人数を除いた差分を計上している。

以上の原因で、マイナスや激増などの現象が出ています。厚労省発表した前日比だけをみると、最近は毎日約4000人を検査しているみたいです（基準変更後のここ数日の話）。
