### ISSUE TITLE
毎日発表される新規数は前日の数字なんですか？

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#390]
毎日発表される新規数は前日の0時〜２４時の数字なんですか？もしくは当時の０時〜発表する時点の数字なんですか？

**Comment by swsoyee** [comment]
感染者数および死者数はリアルタイムの数値で、当日の0時〜発表する時点の分を集計しています。

検査人数と退院者数は厚労省のデータを拾っているので、厚労省は毎日18時前後に当日12時までに集計した数値を発表しています。従って、検査人数と退院者数は主に反映しているのは前日の状況です。0時になってもリセットしません（リセットすると6時間しか表示されないですが、少しややこしいになっているのも事実です）。翌日の18時前後に更新します。
