### ISSUE TITLE
各都道府県の状況のテーブル一覧の都道府県をクリックすると詳細ページに行く

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#391]
サイドバーの自治体状況には北海道青森岩手宮城茨城神奈川しかないですが。

**Comment by swsoyee** [comment]
開発はほとんど一人で担当をしているので、最初は47都道府県全部のページを作りたいですが、流石にキツさを感じました。そろそろ終息するではないかと思いまして、さらに本業にもありますし、計画が一旦中止になりました。本当に申し訳ございません。
