### ISSUE TITLE
About updating 50_Data

### ISSUE THREAD

**Issue by ryo-ma** [swsoyee/2019-ncov-japan#475]
Did you stop updating 50_Data/domesticDailyReport.csv and 50_Data/positiveDetail.csv?

**Comment by swsoyee** [comment]
@ryo-ma Hi, as I mentioned in this issue, https://github.com/ryo-ma/covid19-japan-web-api/issues/29#issuecomment-627241480 You need to update the api.

>  But from May 8, MHLW have changed their structure of daily report, so these file are no longer update anymore. The new version are available here: https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/MHLW/summary.csv
(Maybe @ryo-ma also need to update the api.)

**Comment by ryo-ma** [comment]
OK. Thank! I was overlooking it.
