### ISSUE TITLE
除无症状患者外的统计结果（基于2.17日厚生省统计结果）

### ISSUE THREAD

**Issue by jasonnaruto** [swsoyee/2019-ncov-japan#5]
根据《新型コロナウイルス感染症の現在の状況と厚生労働省の対応について（令和２年２月17日版）》

国内合计检查阳性人数59人，其中无症状12人（但是我没有找到无症状患者的具体地点等数据）
剩余47人中，9例为チャーター便，38例为国内发生

1. 我对这47人进行了基于入院地点的统计。其中チャーター便7例入院地点不明。
（详情请看表格的《各地统计》）

2. 我对《国内发生状况》的编号进行了修正和备注

**Comment by jasonnaruto** [comment]
[基于2.17日版厚生省统计的统计.xlsx](https://github.com/swsoyee/2019-ncov-japan/files/4217460/2.17.xlsx)

**Comment by swsoyee** [comment]
@jasonnaruto 感谢统计，能麻烦一下指出哪一个数据格子有不同之处嘛，拜托了。

比如我核对了
### 和歌山
2/13=1，2/14=1，2/15=3，两份数据相符，和歌山数据没有问题。
### 奈良
1/28=1为正确的，提供的附件`基于2.17日版厚生省统计的统计.xlsx`写的是1/26=1，应该是附件数据错误
参考：[新型コロナウイルスに関連した肺炎の患者の発生について（6例目）](https://www.mhlw.go.jp/stf/newpage_09153.html)

希望能再次确认一下，谢谢～并列举告知我到底是那个县的数据有差错方便修改

**Comment by swsoyee** [comment]
数据问题已修复
