### ISSUE TITLE
連続新規なし日数もしくは、最後感染確認された日を追加

### ISSUE THREAD

**Issue by Lix900** [swsoyee/2019-ncov-japan#520]
できますか？

**Comment by swsoyee** [comment]
@Lix900 少しわかりずらかったかもしれませんが、既にあった機能です。一番右の`0新規日数`は`連続新規なし日数`の意味です。
![image](https://user-images.githubusercontent.com/20528423/83006066-9ff7d780-a04c-11ea-906a-288d9f859414.png)
