### ISSUE TITLE
Japan Data

### ISSUE THREAD

**Issue by emanuele-guidotti** [swsoyee/2019-ncov-japan#571]
Hello and congrats for your work!
I followed your presentation at the CovidR contest, where I presented the COVID-19 Data Hub.
Our project misses the data for Japan and I would love if you could join us and improve our project with your data: https://github.com/covid19datahub/COVID19/

Of course, feel free to close the issue if not interesting for you.
All the best,
-- Emanuele

**Comment by swsoyee** [comment]
Hi, Emanuele,
Congrats for your project `Data Hub` to be the winner!
It's okay for me to add Japan data into your project, but I'm still have lots of work to do, so the  progress may be slow.
Could you provide my a sample PR for me to know how to add my dataset into your project?
Thanks!

**Comment by emanuele-guidotti** [comment]
Great to hear that! 
Yes sure, you can find here a quick tutorial to add new data:
https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source
Just let me know if you need something else or have any question.
Thanks!

**Comment by swsoyee** [comment]
@emanuele-guidotti Thank you! I will try it later.

**Comment by yuanzhouIR** [comment]
I'm also wondering how to integrate the Japanese data into the COVID-19 Data Hub to make it  easier to access. I think the first thing to do is to put the daily confirmed cases, deaths, recovered cases of every prefecture into one single csv file.

@swsoyee I'm pleased to join you for working on this issue.

**Comment by swsoyee** [comment]
@yuanzhouIR Thank you, Zhou! 
I've been so busy lately that I haven't had time to process the data. It would be great if you could help with the issue. 
The description of the entire dataset can be tedious, so it may be convenient to have one discussion in zoom (or wechat) if that is convenient.

**Comment by emanuele-guidotti** [comment]
Thank you @swsoyee and @yuanzhouIR, let me know in case you need some help on the COVID-19 Data Hub side

**Comment by yuanzhouIR** [comment]
> Thank you @swsoyee and @yuanzhouIR, let me know in case you need some help on the COVID-19 Data Hub side

Hi Emanuele, @swsoyee and I are working on the Japan data. In the COVID-19 data released by the Japanese government,  `vent` and `icu` are not distinguished.  There is a variable called `severe`, which is defined as either requiring ventilation or intensive therapy. So I'm wondering how to deal with the `vent` and `icu` variables.

**Comment by emanuele-guidotti** [comment]
Hi, you can put severe cases in a new column named `severe` and I will add it to the dataset with the corresponding documentation

**Comment by eguidotti** [comment]
Hello @yuanzhouIR and @swsoyee, 
I have a doubt about the `severe` cases. As said, it should be `icu` + `vent` correct? On the other hand, I noticed from all other countries worldwide that `vent` is a subset of patients in intensive therapy (`icu`) that also require ventilation. So it seems to me that `vent` + `icu` would count `vent` twice. Could you please double check the definition of `severe` cases for Japan? Maybe it is equivalent to `icu` only? 

From the [Data Hub documentation](https://covid19datahub.io/articles/doc/data.html):

- `icu`: Number of hospitalized patients in ICUs on date.
- `vent`: Number of patients requiring invasive ventilation on date.

Many thanks to both of you for your great work!

**Comment by yuanzhouIR** [comment]
> Hello @yuanzhouIR and @swsoyee,
> I have a doubt about the `severe` cases. As said, it should be `icu` + `vent` correct? On the other hand, I noticed from all other countries worldwide that `vent` is a subset of patients in intensive therapy (`icu`) that also require ventilation. So it seems to me that `vent` + `icu` would count `vent` twice. Could you please double check the definition of `severe` cases for Japan? Maybe it is equivalent to `icu` only?
> 
> From the [Data Hub documentation](https://covid19datahub.io/articles/doc/data.html):
> 
> * `icu`: Number of hospitalized patients in ICUs on date.
> * `vent`: Number of patients requiring invasive ventilation on date.
> 
> Many thanks to both of you for your great work!

Hi @eguidotti , on and before 7 May, severe (critically ill) means cases putting on a ventilator or treated in an Intensive Care Unit (ICU). Since the number is a total of reports from prefectures after that, the definition may vary by prefecture.

As you said, patiennts on ventilator should be also in ICU. However, the Japanese government does not differentiate `icu` and `vent`. They only release the number of severe cases. If we consider all severe cases should be in ICU but not sure if they are on ventilator, we can treat `severe` equivalent to `icu`.

**Comment by eguidotti** [comment]
Hi @yuanzhouIR, thank you for your message. This is really helpful.
I removed the `severe` cases and treated as `icu` in the data hub.
Many thanks!
