### ISSUE TITLE
关于国内事例数据不合问题

### ISSUE THREAD

**Issue by dalaoshi-huster** [swsoyee/2019-ncov-japan#7]
根据厚劳省数据（2020·2·17）
https://www.mhlw.go.jp/stf/newpage_09571.html

第2部分【国内の発生状況について】之记录，PCR阳性人数合计59人，与目前已掌握的数据（54人）存在差距。其中国内事例46例，包机归国13例。

该日报告中，除去撤侨患者后国内事例有38 例（见【国内事例（チャーター便帰国者を除く】）,添加厚生省检疫官员1名后，合计为39人；

另外在【水際対策で確認された事例：武漢市からのチャーター便帰国者に係る発生状況】的（*2）注明另外有4名无症状患者，**应当纳入总数（此处与包机归国例13人之数据吻合）。
以上共计52人。

国内事例尚且有7人不明。目前正在通过浏览houdou.csv逐一排查。

————————————
根据对houdou.csv的报道逐一阅览，现发现
1，厚劳省关于国内感染第37例的记录并未刊载在 2·17的汇总中，望注意。（见  https://www.mhlw.go.jp/stf/newpage_09541.html  ）  该名男子系搬运“钻石公主”号邮轮的职员。当归纳于神奈川县案例。

2,2·13日东京都通报7名阳性患者，似亦未刊载在2·17的汇总中。

3，2·12日通报“钻石公主号”1名登船检疫官员感染，似亦未刊载在2·17的汇总中。

（1,3，已经纳入统计，但不见2月13日东京都的情况）故此合计59人。与总体阳性人数吻合。
当前网站统计的54人可能存在漏记或者某案例重复统计之可能。

——————————————
关于重复统计，你可能将houdou.csv中的告示视作感染通报处理了，例如id42并非病例通报却标记有pre以及resident。

**Comment by swsoyee** [comment]
> 另外在【水際対策で確認された事例：武漢市からのチャーター便帰国者に係る発生状況】的（*2）注明另外有4名无症状患者，应当纳入总数（此处与包机归国例13人之数据吻合）。

根据厚劳省数据，包机归国一共13人，归国后返回埼玉后出现症状的患者不属于国内事例中，需要从现有数据中剔除。修正后埼玉将不会出现在疫情地图中（被归类于包机）。

今晚修正相关数据。

**Comment by swsoyee** [comment]
数据问题已修复
