### ISSUE TITLE
New package should be added into server

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#7163]
### 1.1 CRAN version
- [x] `incidence` (new)
- [x] `EpiEstim` (new)
- [x] `renv` (new)
- [x] `tabulizer` (installed yet?)
- [x] ` jsonlite` (installed yet?)

### 1.2 Github Version
We need to update to the dev version, since some bugs have been fixed in dev version but has not release to CRAN yet.
- [x] `echarts4r`
> Use this command to install github package
> ```r
> remotes::install_github("JohnCoene/echarts4r")
> ```

## 2. Better
- [x] `gtools` (installed yet?)

**Comment by Bob-FU** [comment]
https://hub.docker.com/layers/bobfujp/shiny/422dff1f6131519122f8246837ff1d37eb4b5d82/images/sha256-ba130776401638ddb7b76aaec9af503fd9b1e55b522eed9b6ff6d6d0731e1223?context=repo

docker image pushed.
Require further check before deploy to production server.

**Comment by swsoyee** [comment]
#7168 has been released to production.
