### ISSUE TITLE
Update package version and install new packages

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#7282]
It's seems that only some minor bugs in Heatmap when I test on local.
So I think we are able to just update to the latest dev vesion echarts4r on production.

## Update
- [x] echarts4r
```r
remotes::install_github("JohnCoene/echarts4r")
```

## Install
- [x] bs4Dash
```r
remotes::install_github("RinteRface/bs4Dash")
```

**Comment by Bob-FU** [comment]
Standby for the new docker image being built and uploaded

**Comment by Bob-FU** [comment]
Image has been deployed.
Changes will be applied after next site-release.
