### ISSUE TITLE
コードに書いた文言を全部lang.csvに整理しておく

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#73]
もしどなたが整理していただければ嬉しい🙇🏻‍♂️

**Comment by uribo** [comment]
多言語化とも関連する話題ですね。自治体のページなどは同じ文面が使われているので効果的だと思います 👍 

https://github.com/Appsilon/shiny.i18n

でcsvもしくはjsonを使った管理ができるようですがいかがでしょう？

**Comment by swsoyee** [comment]
どちらで管理しても構いませんと思います。csvファイルの方が言語追加や修正する時やりやすいかもしれませんね。誰もjsonを理解している訳でもないので、csvの場合、プログラマーではない一般の訳者にもExcelで編集できます。

この変の調査もお願いいただけませんかね（すみません頼みばっかりで、、、）

**Comment by uribo** [comment]
ありがとうございます。

> 誰もjsonを理解している訳でもないので、csvの場合、プログラマーではない一般の訳者にもExcelで編集できます。
確かにそうですね。
特に今回のアプリでは開発速度と貢献しやすさが大事かと思うので。
良い方法があれば提案・実装いたします。

**Comment by swsoyee** [comment]
shiny.i18nパッケージ利用、文言修正・翻訳・追加中
