### ISSUE TITLE
Github Actionsによるデータ更新の導入相談について

### ISSUE THREAD

**Issue by uribo** [swsoyee/2019-ncov-japan#74]
`初期化`でコミットメッセージを検索すると毎日 `Data/result.map.csv`を更新されているようですね。

https://github.com/swsoyee/2019-ncov-japan/search?q=初期化&type=Commits

[GitHub Actions](https://github.com/features/actions)等を使った自動化が検討できないでしょうか。
作業負担の軽減になると思います。
（他にも自動化できそうな場所があれば）

参考
- R向けテンプレートと例 https://github.com/r-lib/actions
- 定時実行の例（最近失敗しています...） https://github.com/uribo/japan-covid19/actions

**Comment by swsoyee** [comment]
@uribo Issueありがどうございます！
Github Actionによる自動化もこの間調べてみましたが、試行錯誤する時間はなくて一旦後回ししています。
もちろん一部のところは自動化できます。例えば今毎回データを更新する時、
https://github.com/swsoyee/2019-ncov-japan/blob/master/System/CreateTable.R
を実行して、テーブル表示ためのデータを用意する必要があります。
つい最近までは`pre-commit`を使って`System`フォルダーのスクリプトをcommit時に走らせましたけど、Sparklineを導入（この辺り）
https://github.com/swsoyee/2019-ncov-japan/blob/master/System/CreateTable.R#L145-#L179
した後、なぜか自動的に走らせできなくなりました。（コンソールでGitコマンド実行すると走らせるが自分はGithub Desktopを使っていので、Github Desktopのバグかもしれません）
Script内に日本語のvariableがあるとうまく表示できない（？）原因についてはまだわからないですので、毎回手動的にやってました。

このあたりにもしお願いできればいいと思いますが（私はまだ仕事がありますのでちょっと余裕がなlくてすみません、、）。
1. https://github.com/swsoyee/2019-ncov-japan/blob/master/System/CreateTable.Rでsparklineを作り時、IDがランダム（`<span id="htmlwidget-61f1bee61848aea2b179" `など）に設定されているため、毎回`Data/resultSummaryTable.csv`の差分が大きい。このIDを定数かにしたい。
2. pre-commitではうまくCreateTable.Rを自動的に実行できない（自分のパソコンの環境設定のせいの可能性もあり）ため、Github Actionを使って、毎回byDate.csvが更新される時、CreateTable.Rを走らせ、`Data/resultSummaryTable.csv`を作る

後、作業をもっとシンプルできるために、@uribo さんをCollaboratorに追加したいですがいかがでしょうか。

**Comment by uribo** [comment]
了解です。
ちょっと検討してみますね。
時間のある時にデータ更新時の作業フローを整理していただけると助かります。

Collaboratorへの追加ありがとうございます。どうぞお願いします。
メインの開発はこれまで通り @swsoyee さんに先導してもらって、
後回しにしたものや優先度の低めの処理を
refactoringを含め、改善なりできればと思っています。

**Comment by swsoyee** [comment]
@uribo Inviteしました！作業フローについてできるだけ今夜中にまとめてWikiの方に置きます（できるだけ時間を作ります）！

**Comment by swsoyee** [comment]
@uribo すみません遅くになりました、更新方法を書きました。
https://github.com/swsoyee/2019-ncov-japan/wiki/%E6%89%8B%E5%8B%95%E3%81%A7%E3%83%87%E3%83%BC%E3%82%BF%E6%9B%B4%E6%96%B0%E3%81%AE%E6%96%B9%E6%B3%95

また、`byDate.csv`、`death.csv`、`mhlw_houdou.csv`の自動化更新については @emc-kk さんがご協力できますので、もし可能であれば @uribo さんが`CreateTable.R`を走らせるGithub Actionsの作り方を少し調査お願いできれば嬉しいと思います。

お二人のご協力でデータの自動化更新ができると思います🙇🏻‍♂️

**Comment by uribo** [comment]
Wikiにある
> 情報のソース源（ニュース、報道、記事など）

こちらのデータソースから感染者の情報を見つけてくるのは手動で行われているのですよね？

**Comment by swsoyee** [comment]
@uribo 今のリアルタイムデータ更新系は全て手動でやっています。
https://github.com/swsoyee/2019-ncov-japan/blob/master/00_System/FetchData.R
こちらは半手動でやっています（上流のデータが問題があったら自分のサイトにもそのまま使えないので、毎回手動でアプリを起動して様子がおかしいかどうかのチェックを行う必要があります。
