### ISSUE TITLE
個人用メモ：開発環境をRStudioからVSCodeへの移行

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#79]
RStudioでは開発は便利だが、ファイルの切り替えやJump to、リファクタリングなどちょっと不便と思うので、VSCodeで色々やれるのかを試します。

- [x] VSCodeでRコードの実行
- [x] 自分が設定した`.lintr`がVSCodeにも使えるように
- [ ] VSCodeでShinyアプリを起動できるように

**Comment by uribo** [comment]
参考資料としてどうでしょうか https://speakerdeck.com/andycraig/r-in-visual-studio-code

**Comment by swsoyee** [comment]
@uribo おお、ありがどうございます！後でちょっと試してみます
