### ISSUE TITLE
感染者テーブルのソート不具合

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#81]
- [x] 都道府県のソートにはJISコードにソートすべき（DT周りの設定調査）#83
- [x] 感染者数のソートには数値型のソート方法に使うべき（今はStringになっています） #82
- ~~感染推移のソートは変（ソート必要がある？どういう順番でソートすべき？）~~

**Comment by uribo** [comment]
都道府県のソート、良いですね 👍  
合わせて、一旦保留している #67 も見直しできればと思いますがいかがでしょうか。

**Comment by swsoyee** [comment]
個人的には県1文字を追加しても情報量自体が増えなく、カラムの幅だけがExpandedされました。逆に ヘッダーの 都道府県
を県名に変更したくなりましたがそちらもちょっと微妙と思います。こちらに関してはどう思いますか。

Shinya Uryu <notifications@github.com>于2020年4月19日 周日15:39写道：

**Comment by uribo** [comment]
`感染速報` の表部分ですよね。

![image](https://user-images.githubusercontent.com/228649/79681650-ca3cc500-8256-11ea-9b33-a3dc13e7b138.png)

閲覧環境の問題かもですが、確かに `都道府県` だと文字数が多くて不格好なのですが `県名` にすると `北海道` や `東京都` などは対象外なのかなという印象を持ってしまいます。

個人的には [NHKのページ](https://www3.nhk.or.jp/news/special/coronavirus/medical/) のように ヘッダを `都道府県`、各行の表記は「都・道・府・県」のいずれかを含めた完全な表記にしたいです。

**Comment by swsoyee** [comment]
ではHeaderだけを`行政区域`に変更すれば、「都・道・府・県」問題が微妙に回避できると思いますがどう思いますか（検疫職員のカテゴリは無視）。

**Comment by uribo** [comment]
なるほど。`自治体` は良いですね。

**Comment by swsoyee** [comment]
感染推移のソートに関しては、どのような順番でソートすべきかまだわからないので、バグでもない
（機能改善に近い）ため、こちらのIssueをCloseします。
（週間増加率の順番でソートする？）
