### ISSUE TITLE
データの手動更新から自動更新へ

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/2019-ncov-japan#90]
## 試行フェーズ
1. 朝8時から12時まで45分ごとに一回スクレイピングして[`dataFetchTest`](https://github.com/swsoyee/2019-ncov-japan/tree/dataFetchTest)に対してPRを出す（差分があればPRを出す、なければスキップ）。12時からよるの0時までは15分ごとにスクレイピングしてPRを出す。
2. マージされたらGithub Actionで`CreateTable.R`を走らせて、作成されたファイルを自動コミットする。
3. Github Actionが実行終わった後にCIを走らせ、Deployする。

まずは、`dataFetchTest`で1と2のテストをして、piplineが問題なければ、そのpiplelineを`dev`ブランチでテストする（3のテストをするため）。

@Bob-FU @emc-kk @uribo お邪魔してすみません、この部分に関しては自分は知見ゼロですので、多分みなさんの協力が必要と思います。よろしくお願いします。

**Comment by uribo** [comment]
> スクレイピング

ここの処理はRファイルになっていますか？または対象のウェブページが決まっているとかあります？

**Comment by swsoyee** [comment]
スクレイピングは @emc-kk さんが担当しています。多分JSと思います。対象のウェブページは自分が今まで参考にしたJX通信社の集計サイトです。https://newsdigest.jp/pages/coronavirus/

JX通信社のデータは一番早いが、集計ミスも結構出ているが、後から修正もされていますので、現時点においては信頼できるソースです（私のサイトも今までJX通信社のデータを参考にしているので、confilctがなさそうです）。

**Comment by emc-kk** [comment]
スクレイピング自体はPythonでやっていて、PR自動化自体はEC2建てて、crontabで制御予定になります！
あまりbash等詳しくないので、こちら自動化色々伺うかもしれませんが、よろしくお願い致します🙇‍♂️

**Comment by emc-kk** [comment]
ただいまの完了ステータス
データをスクレイピングにより取得

次の必要項目
「データ差分をチェックし、データをCSV形式に加工
その上でPR」
という流れを構築し、自動化する

**Comment by emc-kk** [comment]
@swsoyee さん
データ管理している該当のCSVがどこにあるか忘れてしまい、、
再度ご教示頂けると嬉しいです🙇‍♂️

**Comment by swsoyee** [comment]
@emc-kk 新規は
byDate.csvと記事リンク集mhlw_houdou.csvを更新します。
https://github.com/swsoyee/2019-ncov-japan/commit/47f7b1513e3a1e54c237a93dfb058bfb29c2359d
死亡は
death.csvと記事リンク集mhlw_houdou.csvを更新します。

result.map.csvとresultSummaryTable.csv ファイルは自動生成されたファイルです。更新が
あったらCreateTable.RをGithub Actionsで実行すればその二つのファイルが更新されます。

**Comment by emc-kk** [comment]
@swsoyee さん
ありがとうございます！

PR自動化としては、
差分checkして感染者がいた場合→byDate.csvと記事リンク集mhlw_houdou.csvを更新
差分checkして死亡者がいた場合→death.csvと記事リンク集mhlw_houdou.csvを更新
どちらもの場合→どちらも更新
をすると認識しました。

こちらPR後のmergeが必要になると思うのですが、CreateTable.Rをactionsで実行するタスクも自動化範囲内でしょうか？

**Comment by swsoyee** [comment]
> CreateTable.Rをactionsで実行するタスクも自動化範囲内でしょうか？

そうですね。可能であれば、PRを出した時点でCreateTable.Rが実行済みな状態になった方がいいかもしれません。そしたらマージされたらそのままサーバーにDeployできますので。

もし難しいであれば、またやり方を考えましょう。

**Comment by emc-kk** [comment]
かしこまりました！
一旦PR自動化（データ追加まで）を作って考えてみます。

**Comment by emc-kk** [comment]
お疲れ様です。
昨日作業できず、申し訳ございません。

本日pullrequestの自動化のテストをしたいと考えているのですが、branchは以下を使うイメージでよろしいでしょうか？
https://github.com/swsoyee/2019-ncov-japan/tree/dataFetchTest

**Comment by swsoyee** [comment]
はい、大丈夫です。またブランチを作っても大丈夫です。

emckk <notifications@github.com>于2020年4月26日 周日07:29写道：

**Comment by emc-kk** [comment]
かしこまりました、ありがとうございます！

本日恐らくテストのため少しうるさくなりますが、スルーしてください🙇‍♂️

**Comment by emc-kk** [comment]
お疲れ様です！

こちら自動化処理行ったのですが、現在の時間更新されていないためテストができておりません。

一応追加情報をSlackで通知が来るようにしたのと、自動的にgitを操作してprを出すようにスクリプト（以下記載）書いたのですが、初めてbashスクリプトでgitを管理するので自信がないです。

`cd /home/ec2-user/database_update/git/2019-ncov-japan/ && git add /home/ec2-user/database_update/git/2019-ncov-japan/50_Data/byDate.csv /home/ec2-user/database_update/git/2019-ncov-japan/50_Data/death.csv /home/ec2-user/database_update/git/2019-ncov-japan/50_Data/mhlw_houdou.csv && git commit -m "data update" && git push && pr data_update test_update`

prコマンドは以下を参考にしています。
[参考](https://qiita.com/IZUMIRU/items/e1c86fa993287ef5bdeb)

なお、gitのユーザー名パスワードはglobalに設定してあり、それは問題なさそうです。

今から寝るので、もしかしたら上記がうまくいっていて、PR出しちゃってるかもしれないです。
その時は申し訳ございません🙇‍♂️

**Comment by emc-kk** [comment]
あ、大事なこと伝え忘れていました。
本日付で差分チェックと自動的なcsv管理まではできております。
PRの自動化に手こずってしまっているという現状になります。（上記でうまくいっている可能性も否定できませんが、自信がありません。）

**Comment by swsoyee** [comment]
@emc-kk ありがどうございます！ではとりあえず今日少し様子を見てやりましょう。Github Actionsでの設定もまだですので、調整しつつやるという感じです。

**Comment by swsoyee** [comment]
@uribo お疲れ様です、データの取得は既に @emc-kk の協力によってできているみたいです（ありがどうございます！）PRはだいたい以下のようになります。
https://github.com/swsoyee/2019-ncov-japan/pull/130/files

もし大丈夫でしたら、@uribo さんにGithub Actionsに少しWorkflowを設定いただきたいと思いますが、PRをマージした後、こちらのスクリプト
https://github.com/swsoyee/2019-ncov-japan/blob/master/00_System/CreateTable.R
を走らせて、自動作成されたファイルを追加コミットするということは可能でしょうか。

もし可能であれば、`byDate.csv`と`death.csv`が変更がある場合のみ走らせる、難しいであれば、PRをマージした後に実行すればOkと思います。

**Comment by uribo** [comment]
承知です。挑戦してみます。

@swsoyee 
> PRをマージした後、こちらのスクリプト
https://github.com/swsoyee/2019-ncov-japan/blob/master/00_System/CreateTable.R
を走らせて、自動作成されたファイルを追加コミット

こちらはmasterブランチへのpush設定で構いませんか？

@emc-kk 
データ追加のプルリクエストを他のプルリクエストと分けるために、プルリクエストに対してラベルを設定することはできますでしょうか。

**Comment by swsoyee** [comment]
> データ追加のプルリクエストを他のプルリクエストと分けるために、プルリクエストに対してラベルを設定することはできますでしょうか。

こちら自分設定済みです。

自分もちょっとだけ試しました、そろそろできているっぽい？
https://github.com/swsoyee/2019-ncov-japan/blob/master/.github/workflows/main.yml

ただ：
1. このActionは、実行したあとの結果は該当PRに追加しているわけではなく、直接MasterにCommitしているらしい？（設定ミスかそれとも勘違いか要確認）もし何かご存知たらご指摘お願い致します。

**Comment by swsoyee** [comment]
@uribo @emc-kk ありがどうございます！
先程少しActionsの結果を見まして、できているみたいです！

本当にありがどうございます！（これからデータ更新の作業負担も十分減りましたね、感想👍）
